version: '3.8'

services:
  db:
    container_name: autospace_db
    image: postgres
    restart: always
    ports:
      - 2010:5432
    environment:
      POSTGRES_USER: neondb_owner
      POSTGRES_DB: neondb
      POSTGRES_PASSWORD: npg_E8c2xUGjOaRz
    volumes:
      - db_data_autospace:/var/lib/postgresql/data
volumes:
  db_data_autospace:
